### ISSUE TITLE
Library expects Base64 input file

### ISSUE THREAD

**Issue by McPo** [enricodeleo/JSCryptor-cli#1]
It appears the library requires a file to be encoded to base64 before being decrypted within the library. This is not what I would have expected.

**Comment by enricodeleo** [comment]
Hi @McPo. Even if this module is based upon the javascript implementation of RNCryptor (https://github.com/chesstrian/JSCryptor) that is mainly tested on strings, nor me neither the develper of the library assumed just base64 strings so it _**should**_ work with any data.

As you may know Javascript in general is not the better place for binary data, so base64 encrypting (that in fact is a string representation of data) would be a safer choice.
